app:
  name: "RadRAG"
  version: "1"

# Chunking Avançado
advanced_chunking:
  strategy: "semantic_hierarchical"  # hierarchical, semantic, hybrid ou semantic_hierarchical (ensemble - semantic + hierarchical)

  # Configurações hierárquicas
  parent_chunk_size: 800
  parent_overlap: 200
  child_chunk_size: 200
  child_overlap: 50

  # Configurações semânticas
  similarity_threshold: 0.75
  buffer_size: 1

  # Limites gerais
  min_chunk_size: 50
  max_chunk_size: 500

# ChromaDB
chromadb:
  persist_directory: "./chroma_db"
  collection_name: "cnen_bge_m3_chunks"
  distance_function: "cosine"
  embedding_dimension: 1024  # BAAI/bge-m3 usa 1024 dimensões

  # Configurações de busca
  search:
    type: "hybrid"  # semantic, keyword, ou hybrid
    semantic_weight: 0.7
    keyword_weight: 0.3
    rerank_results: true

# LLM para geração de respostas
llm:
  model: "llama3.1:latest"
  base_url: "http://localhost:11434"
  temperature: 0.1
  max_tokens: 1000

# Embeddings - BAAI/bge-m3 (modelo multilíngue de alta performance)
embeddings:
  model: "BAAI/bge-m3"  
  device: "cpu"  # Trocar para "cuda" se tiver GPU 
  batch_size: 12  # Reduzido para bge-m3 (maior modelo)/ Aumenta ou diminui o tempo de processamento
  max_length: 512
  normalize: true
  use_fp16: false  # Trocar para true com GPU

# Retrieval
retrieval:
  # Busca inicial
  top_k_initial: 20

  # Após reranking
  top_k_final: 4

  # Thresholds
  min_relevance_score: 0.5

  # Estratégia de busca
  use_parent_context: true  # Incluir parent quando retornar child
  context_window: 2  # Chunks adjacentes para contexto

# Reranker - CrossEncoder para melhorar relevância dos resultados
reranker:
  enabled: true  # Ativar/desativar reranking
  model: "BAAI/bge-reranker-v2-m3"  # Modelo cross-encoder
  device: "cuda:0"  # cuda:0, cuda:1, ou cpu
  batch_size: 32  # Tamanho do batch para reranking
  top_k_rerank: 20  # Quantos resultados iniciais considerar para reranking

  # Modelos alternativos:
  # - "cross-encoder/ms-marco-MiniLM-L-6-v2" (mais rápido, menos preciso)
  # - "cross-encoder/ms-marco-MiniLM-L-12-v2" (balanceado)
  # - "cross-encoder/ms-marco-TinyBERT-L-2-v2" (muito rápido para CPU)
  # - "BAAI/bge-reranker-base" (multilíngue)
  # - "BAAI/bge-reranker-large" (melhor qualidade, mais lento)
  # cross-encoder/ms-marco-electra-base
  # BAAI/bge-reranker-v2-m3

# Performance
performance:
  cache_embeddings: true
  cache_directory: "./cache"
  parallel_processing: true
  num_workers: 4

# Logging
logging:
  level: "INFO"  # DEBUG, INFO, WARNING, ERROR
  file: "logs/rag_system.log"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
